# Generated by Django 2.1.7 on 2019-11-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.CharField(max_length=32, verbose_name='工作流状态')),
                ('action_type', models.SmallIntegerField(choices=[(1, '批准'), (2, '拒绝'), (3, '取消'), (4, '重新启动'), (5, '解决')], default=1, verbose_name='状态类型')),
                ('description', models.CharField(max_length=32, verbose_name='状态描述')),
            ],
            options={
                'verbose_name_plural': '工作状态表',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='流程标识')),
                ('state', models.BooleanField(default=True, verbose_name='流程状态')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='流程描述')),
            ],
            options={
                'verbose_name_plural': '工作流程表',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.CharField(max_length=32, verbose_name='工作流状态')),
                ('state_type', models.SmallIntegerField(choices=[(1, '开始'), (2, '正常'), (3, '完成'), (4, '拒绝'), (5, '已取消')], default=1, verbose_name='状态类型')),
                ('description', models.CharField(max_length=32, verbose_name='状态描述')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Process', verbose_name='所属流程的id')),
            ],
            options={
                'verbose_name_plural': '工作状态表',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('current_state_id', models.IntegerField(verbose_name='当前状态id')),
                ('next_state_id', models.IntegerField(verbose_name='下一状态id')),
                ('action_id', models.IntegerField(verbose_name='所属流程操作id')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Process', verbose_name='所属流程的id')),
            ],
            options={
                'verbose_name_plural': '工作流转表',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Process', verbose_name='所属流程的id'),
        ),
    ]
