# Generated by Django 2.1.7 on 2019-11-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20191129_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='role_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.RoleGroup', verbose_name='角色项目组'),
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.RoleGroup', verbose_name='项目角色组'),
        ),
    ]
