# Generated by Django 2.1.7 on 2019-11-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20191129_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='role_group',
            field=models.IntegerField(verbose_name='项目角色组id'),
        ),
    ]
