# Generated by Django 2.1.7 on 2019-12-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20191129_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group2Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.RoleGroup', verbose_name='角色组')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.AddField(
            model_name='group2roles',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Role', verbose_name='角色'),
        ),
    ]
