# Generated by Django 2.1.7 on 2019-12-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20191204_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='roles_list',
            field=models.CharField(default='', max_length=30, verbose_name='有权限执行的角色列表'),
        ),
    ]
