# Generated by Django 2.1.7 on 2019-12-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_transition_roles_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('resourceId', models.IntegerField(verbose_name='请求ID')),
                ('resourceType', models.SmallIntegerField(choices=[(1, '项目发布'), (2, '运维工单申请')], default=1, verbose_name='请求类型')),
                ('processId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Process', verbose_name='工作流表')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
