# Generated by Django 2.1.7 on 2019-12-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resourceId',
            field=models.IntegerField(null=True, verbose_name='请求ID'),
        ),
    ]
