# Generated by Django 2.1.7 on 2019-12-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20191210_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='请求类型')),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ResourceType', verbose_name='请求类型'),
        ),
    ]
