# Generated by Django 2.1.7 on 2019-12-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20191210_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='type',
            field=models.CharField(max_length=30, unique=True, verbose_name='请求类型'),
        ),
    ]
