# Generated by Django 2.1.7 on 2019-12-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20191211_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('type', models.CharField(max_length=30, unique=True, verbose_name='请求类型')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='请求类型code')),
                ('processId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Process', verbose_name='工作流表')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resource',
            name='processId',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resourceType',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
