# Generated by Django 2.1.7 on 2020-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_orderrolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='', max_length=100)),
                ('image_select', models.ImageField(upload_to='media/images/%Y-%m/')),
            ],
            options={
                'verbose_name': '图片集合',
                'verbose_name_plural': '图片集合',
            },
        ),
    ]
