# Generated by Django 2.1.7 on 2020-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_imageitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitems',
            name='image_select',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片路径'),
        ),
    ]
