# Generated by Django 2.1.7 on 2020-07-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20200706_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageItems',
        ),
    ]
