# Generated by Django 2.1.7 on 2019-11-29 05:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='方法名称')),
                ('action', models.CharField(max_length=32, unique=True, verbose_name='方法')),
            ],
            options={
                'verbose_name_plural': '请求方法表',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='权限名称')),
                ('url', models.CharField(max_length=32, verbose_name='接口地址')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method', to='user.Method')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Permission', verbose_name='父权限')),
            ],
            options={
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='角色名称')),
                ('desc', models.CharField(default='', max_length=32, verbose_name='角色描述')),
                ('permission', models.ManyToManyField(blank=True, to='user.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='最后登入时间')),
                ('last_login_ip', models.CharField(max_length=20, null=True, verbose_name='上次登入IP')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('department', models.CharField(max_length=32, null=True, verbose_name='部门')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('avatar', models.FileField(default='avatar/default.jpeg', upload_to='avatar')),
                ('account_expr', models.DateField(null=True, verbose_name='密码过期时间')),
                ('is_supper', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('uuid', models.UUIDField(default=uuid.UUID('d6fa49f0-57b7-44f6-a7f8-52271bd0244f'), verbose_name='用户JWT密钥')),
                ('role', models.ManyToManyField(related_name='role', to='user.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
