# Generated by Django 2.1.7 on 2019-11-29 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191129_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7f91ff73-bee3-4fe7-8aa2-567e976baac6'), verbose_name='用户JWT密钥'),
        ),
    ]
