# Generated by Django 2.1.7 on 2019-11-29 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191129_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('66cc2d60-a664-4b70-a8b6-58dd0a645d47'), verbose_name='用户JWT密钥'),
        ),
    ]
