# Generated by Django 2.1.7 on 2019-12-04 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191129_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aa706f8a-6ed8-4e90-be54-01aae6b5c0f6'), verbose_name='用户JWT密钥'),
        ),
    ]
