# Generated by Django 2.1.7 on 2019-12-05 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191204_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2541c68d-4c6d-4352-bf43-5ac4939f8c6f'), verbose_name='用户JWT密钥'),
        ),
    ]
