# Generated by Django 2.1.7 on 2019-12-09 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191205_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b2481e27-96af-473f-8240-19ff142c6f0b'), verbose_name='用户JWT密钥'),
        ),
    ]
