# Generated by Django 2.1.7 on 2019-12-10 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191209_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1b4c71c2-de1c-4a62-bb2a-75774d9286e7'), verbose_name='用户JWT密钥'),
        ),
    ]
