# Generated by Django 2.1.7 on 2019-12-10 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191210_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b51dd709-4d5b-4104-ad13-08f909464df2'), verbose_name='用户JWT密钥'),
        ),
    ]
