# Generated by Django 2.1.7 on 2019-12-11 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191210_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('46d20d63-c330-4ff2-b063-6027b0f8027e'), verbose_name='用户JWT密钥'),
        ),
    ]
