# Generated by Django 2.1.7 on 2019-12-13 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191212_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('95a0d53c-814b-4e13-bd60-e53c498e9a68'), verbose_name='用户JWT密钥'),
        ),
    ]
