# Generated by Django 2.1.7 on 2020-03-11 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200311_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e8dbd069-2b02-4440-9398-7c7485756b65'), verbose_name='用户JWT密钥'),
        ),
    ]
