# Generated by Django 2.1.7 on 2020-03-11 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200311_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('940b7434-b1d1-45de-83c9-684ff9917fca'), verbose_name='用户JWT密钥'),
        ),
    ]
