# Generated by Django 2.1.7 on 2020-03-26 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200311_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8faa7dd7-e583-4cb7-a86c-933c37abe984'), verbose_name='用户JWT密钥'),
        ),
    ]
