# Generated by Django 2.1.7 on 2020-05-20 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200330_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1126d49b-9b4a-4f5f-995d-364f2d959ed8'), verbose_name='用户JWT密钥'),
        ),
    ]
