# Generated by Django 2.1.7 on 2020-05-20 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200520_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5ad34a12-f72a-49b1-96ac-a9325f5d77a7'), verbose_name='用户JWT密钥'),
        ),
    ]
