# Generated by Django 2.1.7 on 2020-05-20 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20200520_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a31e24b0-76e9-4ef7-b602-94356c72e148'), verbose_name='用户JWT密钥'),
        ),
    ]
