# Generated by Django 2.1.7 on 2020-06-02 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200520_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('91aae97b-a4b4-4d42-85dc-a07cb173fbce'), verbose_name='用户JWT密钥'),
        ),
    ]
