# Generated by Django 2.1.7 on 2020-06-03 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200602_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2cc370a7-272f-4c12-af28-a3b79af92b8f'), verbose_name='用户JWT密钥'),
        ),
    ]
