# Generated by Django 2.1.7 on 2020-06-10 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200603_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('88c7f193-1406-4f40-a837-7bd39d0749d3'), verbose_name='用户JWT密钥'),
        ),
    ]
