# Generated by Django 2.1.7 on 2020-06-10 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20200610_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c91b2c2f-5e43-4a1e-9631-9eb0426f3291'), verbose_name='用户JWT密钥'),
        ),
    ]
