# Generated by Django 2.1.7 on 2020-06-12 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20200612_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fcb53f31-c565-4246-9ea6-ad629816d44b'), verbose_name='用户JWT密钥'),
        ),
    ]
