# Generated by Django 2.1.7 on 2020-06-17 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20200612_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a5e5c7c4-f016-44bd-8893-2b2b21e24bf4'), verbose_name='用户JWT密钥'),
        ),
    ]
