# Generated by Django 2.1.7 on 2020-06-19 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20200617_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e5b0bd3b-bd4f-4232-b8fa-b87f40727ba2'), verbose_name='用户JWT密钥'),
        ),
    ]
