# Generated by Django 2.1.7 on 2020-07-06 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20200619_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f3be1b49-a61f-49df-8849-c00dd97e9a24'), verbose_name='用户JWT密钥'),
        ),
    ]
