# Generated by Django 2.1.7 on 2020-07-06 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20200706_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('10ede163-5e59-47ee-ade7-8b1df2e04f22'), verbose_name='用户JWT密钥'),
        ),
    ]
