# Generated by Django 2.1.7 on 2020-07-06 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20200706_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('df45e2f2-4658-4e7d-945f-dda7588484fa'), verbose_name='用户JWT密钥'),
        ),
    ]
