# Generated by Django 2.1.7 on 2020-10-09 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20201009_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ba947101-a15b-460a-8e80-cf22c2db3719'), verbose_name='用户JWT密钥'),
        ),
    ]
