# Generated by Django 2.1.7 on 2020-10-09 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20201009_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7a81c55d-d74b-495f-8e69-bc2495da8544'), verbose_name='用户JWT密钥'),
        ),
    ]
