# Generated by Django 2.1.7 on 2020-10-13 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20201009_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('298a675c-da1e-488b-a798-ebefaed9ed22'), verbose_name='用户JWT密钥'),
        ),
    ]
