# Generated by Django 2.1.7 on 2020-10-15 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20201014_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('feaa715c-943b-4f9b-b123-cb8d66e8b167'), verbose_name='用户JWT密钥'),
        ),
    ]
