# Generated by Django 2.1.7 on 2020-10-15 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20201015_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1c6bcb02-682a-4714-b81d-ec960445f0ce'), verbose_name='用户JWT密钥'),
        ),
    ]
