# Generated by Django 2.1.7 on 2020-11-03 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20201015_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('11543d0a-69ea-4f9b-a8f0-6f3bc99d6433'), verbose_name='用户JWT密钥'),
        ),
    ]
