# Generated by Django 2.1.7 on 2020-11-04 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20201103_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c08e6bdc-3006-43e8-8c17-bc69b12aefe2'), verbose_name='用户JWT密钥'),
        ),
    ]
