# Generated by Django 2.1.7 on 2020-11-04 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20201104_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fe769519-40c6-4a29-87a5-9fd47aca98fe'), verbose_name='用户JWT密钥'),
        ),
    ]
