# Generated by Django 2.1.7 on 2020-11-05 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20201104_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d5929be5-d690-41bc-8bb4-4efa94cf38de'), verbose_name='用户JWT密钥'),
        ),
    ]
