# Generated by Django 2.1.7 on 2020-11-05 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20201105_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5eeaaabd-517d-4f89-8489-f8e50887c976'), verbose_name='用户JWT密钥'),
        ),
    ]
