# Generated by Django 2.1.7 on 2020-12-03 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_auto_20201105_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default='', max_length=64, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1cfb8f1c-636f-4004-86f4-68c2b4f7562a'), verbose_name='用户JWT密钥'),
        ),
    ]
