# Generated by Django 2.1.7 on 2022-07-01 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20220701_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('191ba223-baf1-45ab-9281-c2ee8dbc55a5'), verbose_name='用户JWT密钥'),
        ),
    ]
