# Generated by Django 2.1.7 on 2022-07-01 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20220701_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1b8af779-7539-4a32-8d31-f724c61dfd76'), verbose_name='用户JWT密钥'),
        ),
    ]
