# Generated by Django 2.1.7 on 2023-03-21 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20220701_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('792cfd55-c646-4094-a781-7454e195afdf'), verbose_name='用户JWT密钥'),
        ),
    ]
