# Generated by Django 2.1.7 on 2020-05-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0013_orderrolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPSWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('synopsis', models.CharField(max_length=32, verbose_name='概要')),
                ('operator', models.CharField(default='', max_length=20, verbose_name='经办人')),
                ('proposer', models.CharField(default='', max_length=20, verbose_name='申请人')),
                ('describe', models.TextField(verbose_name='描述')),
                ('environment', models.SmallIntegerField(choices=[(1, '开发环境'), (2, '测试环境'), (3, '预生产环境'), (4, '生产环境')], default=1, verbose_name='环境')),
                ('priority', models.SmallIntegerField(choices=[(1, '低'), (2, '中等'), (3, '高'), (4, '紧急')], default=1, verbose_name='优先级')),
                ('current_state_id', models.CharField(default='', max_length=20, verbose_name='当前状态')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.WorkType', verbose_name='工单类型')),
            ],
            options={
                'verbose_name_plural': '工单表',
            },
        ),
    ]
