# Generated by Django 2.1.7 on 2020-06-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPSWorkOrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('begin_status', models.CharField(default='', max_length=20, verbose_name='变更前状态')),
                ('after_status', models.CharField(default='', max_length=20, verbose_name='变更后状态')),
                ('begin_operator', models.CharField(default='', max_length=20, verbose_name='变更前经办人')),
                ('after_operator', models.CharField(default='', max_length=20, verbose_name='变更后经办人')),
                ('operator', models.CharField(default='', max_length=20, verbose_name='实际经办人')),
                ('desc', models.CharField(blank=True, max_length=512, verbose_name='备注信息')),
                ('note', models.CharField(blank=True, max_length=20, verbose_name='状态标题')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OPSWorkOrder', verbose_name='工单id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
