# Generated by Django 2.1.7 on 2020-06-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_opsworkorderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsworkorder',
            name='typeList',
            field=models.CharField(default='', max_length=20, verbose_name='工单类型列表'),
        ),
    ]
