# Generated by Django 2.1.7 on 2020-10-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deploy', '0021_remove_subproject_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('configuration', models.CharField(max_length=30, verbose_name='主机配置')),
                ('OS', models.SmallIntegerField(choices=[(1, 'Linux'), (2, 'Windows')], default=1, verbose_name='主机系统')),
                ('env', models.SmallIntegerField(choices=[(1, '预生产环境'), (2, '生产环境'), (3, '测试环境'), (4, '开发环境')], default=1, verbose_name='主机环境')),
            ],
            options={
                'verbose_name_plural': '主机信息表',
            },
        ),
        migrations.CreateModel(
            name='HostToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.HostInfo', verbose_name='主机ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Project', verbose_name='项目id')),
            ],
        ),
    ]
