# Generated by Django 2.1.7 on 2020-10-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='OS',
        ),
        migrations.RemoveField(
            model_name='hostinfo',
            name='configuration',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='CPU',
            field=models.CharField(default='', max_length=10, verbose_name='cpu'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='OSName',
            field=models.CharField(default='', max_length=30, verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='OSType',
            field=models.CharField(default='', max_length=20, verbose_name='系统类型'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='memory',
            field=models.CharField(default='', max_length=10, verbose_name='内存'),
        ),
    ]
