# Generated by Django 2.1.7 on 2020-10-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20201013_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP地址'),
        ),
    ]
