# Generated by Django 2.1.7 on 2020-11-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_hostinfo_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='sshTag',
            field=models.BooleanField(default=True, verbose_name='是否可以用ssh链接'),
        ),
    ]
