# Generated by Django 2.1.7 on 2020-11-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_hostinfo_sshtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('nid', models.IntegerField(verbose_name='用户ID')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('cmd', models.CharField(max_length=64, verbose_name='操作命令')),
            ],
            options={
                'verbose_name_plural': 'ssh操作日志表',
            },
        ),
    ]
