# Generated by Django 2.1.7 on 2020-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_hostaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostaccesslog',
            name='access_user',
            field=models.CharField(default='', max_length=10, verbose_name='操作用户'),
        ),
    ]
