# Generated by Django 2.1.7 on 2020-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_hostaccesslog_access_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostaccesslog',
            name='cmd',
            field=models.CharField(max_length=255, verbose_name='操作命令'),
        ),
    ]
