# Generated by Django 2.1.7 on 2020-11-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_auto_20201105_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostAccessLog',
        ),
    ]
