# Generated by Django 2.1.7 on 2022-07-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('synopsis', models.CharField(max_length=32, verbose_name='概要')),
                ('operator', models.CharField(default='', max_length=20, verbose_name='经办人')),
                ('proposer', models.CharField(default='', max_length=20, verbose_name='申请人')),
                ('describe', models.TextField(verbose_name='描述')),
                ('deployTags', models.SmallIntegerField(choices=[(1, '定制化发布'), (2, '标准化发布')], default=1, verbose_name='发布类型')),
                ('priority', models.SmallIntegerField(choices=[(1, '低'), (2, '中等'), (3, '高'), (4, '紧急')], default=1, verbose_name='优先级')),
                ('current_state_id', models.CharField(default='', max_length=20, verbose_name='当前状态')),
            ],
            options={
                'verbose_name_plural': '工单表',
            },
        ),
        migrations.CreateModel(
            name='LocalOrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('begin_status', models.CharField(default='', max_length=20, verbose_name='变更前状态')),
                ('after_status', models.CharField(default='', max_length=20, verbose_name='变更后状态')),
                ('begin_operator', models.CharField(default='', max_length=20, verbose_name='变更前经办人')),
                ('after_operator', models.CharField(default='', max_length=20, verbose_name='变更后经办人')),
                ('operator', models.CharField(default='', max_length=20, verbose_name='实际经办人')),
                ('desc', models.CharField(blank=True, max_length=512, verbose_name='备注信息')),
                ('note', models.CharField(blank=True, max_length=20, verbose_name='状态标题')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localDeploy.LocalOrder', verbose_name='工单id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名')),
                ('projectTags', models.SmallIntegerField(choices=[(1, '定制化项目'), (2, '标准化项目')], default=1, verbose_name='项目类型')),
                ('describe', models.TextField(verbose_name='项目描述')),
            ],
            options={
                'verbose_name_plural': '项目信息表',
            },
        ),
        migrations.AddField(
            model_name='localorder',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localDeploy.LocalProject', verbose_name='项目id'),
        ),
    ]
