# Generated by Django 2.1.7 on 2023-03-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localDeploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localproject',
            name='companyCode',
            field=models.CharField(default='', max_length=32, verbose_name='企业编号'),
        ),
        migrations.AlterField(
            model_name='localproject',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='企业名称'),
        ),
    ]
