# Generated by Django 2.1.7 on 2023-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localDeploy', '0002_auto_20230321_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='localorder',
            name='patch',
            field=models.CharField(default='', max_length=20, verbose_name='概要'),
        ),
    ]
