# Generated by Django 2.1.7 on 2019-11-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名')),
                ('describe', models.TextField(verbose_name='项目描述')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Process', verbose_name='所属工作流id')),
            ],
            options={
                'verbose_name_plural': '项目信息表',
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目角色')),
                ('describe', models.TextField(verbose_name='角色描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名')),
                ('describe', models.TextField(verbose_name='项目描述')),
                ('type', models.SmallIntegerField(choices=[(1, '前端'), (2, '后端')], default=1, verbose_name='项目类型')),
                ('command', models.CharField(default='', max_length=512, verbose_name='项目命令')),
                ('git_address', models.CharField(default='', max_length=512, verbose_name='git地址')),
                ('interface_name', models.CharField(default='', max_length=32, verbose_name='接口名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Project', verbose_name='一级项目')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('synopsis', models.CharField(max_length=32, verbose_name='概要')),
                ('operator', models.CharField(default='', max_length=20, verbose_name='经办人')),
                ('proposer', models.CharField(default='', max_length=20, verbose_name='申请人')),
                ('describe', models.TextField(verbose_name='描述')),
                ('released_list', models.CharField(max_length=512, verbose_name='需要发布的工程')),
                ('environment', models.SmallIntegerField(choices=[(1, '预生产环境'), (2, '生产环境')], default=1, verbose_name='发布环境')),
                ('manual_tags', models.BooleanField(default=False, verbose_name='手动发布标签')),
                ('priority', models.SmallIntegerField(choices=[(1, '低'), (2, '中等'), (3, '高'), (4, '紧急')], default=1, verbose_name='优先级')),
                ('current_state_id', models.IntegerField(verbose_name='当前状态ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Project', verbose_name='项目id')),
            ],
            options={
                'verbose_name_plural': '发布工单表',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可执行')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Action', verbose_name='所属工作流动作id')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.WorkOrder', verbose_name='工单id')),
                ('transition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Transition', verbose_name='所属工作流流转id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('begin_status', models.CharField(default='', max_length=20, verbose_name='变更前状态')),
                ('after_status', models.CharField(default='', max_length=20, verbose_name='变更后状态')),
                ('begin_operator', models.CharField(default='', max_length=20, verbose_name='变更前经办人')),
                ('after_operator', models.CharField(default='', max_length=20, verbose_name='变更后经办人')),
                ('operator', models.CharField(default='', max_length=20, verbose_name='实际经办人')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='备注信息')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.WorkOrder', verbose_name='工单id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
