# Generated by Django 2.1.7 on 2019-11-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRole',
        ),
    ]
