# Generated by Django 2.1.7 on 2019-12-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_delete_projectrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='ConfigCenter',
            field=models.CharField(default='', max_length=128, verbose_name='配置中心文件'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='PackageName',
            field=models.CharField(default='', max_length=64, verbose_name='编译target目录'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='ProjectName',
            field=models.CharField(default='', max_length=64, verbose_name='项目目录'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='ansible_group',
            field=models.CharField(default='', max_length=64, verbose_name='ansible主机组名称'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='env',
            field=models.CharField(default='dev', max_length=32, verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='job_name',
            field=models.CharField(default='', max_length=64, verbose_name='jobname'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='label',
            field=models.CharField(default='', max_length=32, verbose_name='maven编译标签'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='webapp_dir',
            field=models.CharField(default='', max_length=128, verbose_name='项目存放路径'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'static'), (2, 'tomcat'), (3, 'python'), (4, 'go')], default=2, verbose_name='项目类型'),
        ),
    ]
