# Generated by Django 2.1.7 on 2019-12-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20191204_1517'),
        ('deploy', '0003_auto_20191202_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project2Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('processId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Process', verbose_name='工作流表')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='process_id',
        ),
        migrations.AddField(
            model_name='project2process',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Project', verbose_name='项目名称'),
        ),
    ]
