# Generated by Django 2.1.7 on 2019-12-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20191202_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Process', verbose_name='所属工作流id'),
        ),
    ]
