# Generated by Django 2.1.7 on 2019-12-05 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20191204_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderaction',
            name='action_id',
        ),
        migrations.RemoveField(
            model_name='workorderaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='workorderaction',
            name='transition_id',
        ),
        migrations.DeleteModel(
            name='WorkOrderAction',
        ),
    ]
