# Generated by Django 2.1.7 on 2019-12-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_auto_20191203_1634'),
        ('deploy', '0005_auto_20191205_1054'),
    ]

    operations = [
    ]
