# Generated by Django 2.1.7 on 2019-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_merge_20191209_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project2process',
            name='processId',
        ),
        migrations.RemoveField(
            model_name='project2process',
            name='projectId',
        ),
        migrations.AlterField(
            model_name='subproject',
            name='ansible_group',
            field=models.CharField(default='', max_length=64, verbose_name='ansible主机组名称'),
        ),
        migrations.DeleteModel(
            name='Project2Process',
        ),
    ]
