# Generated by Django 2.1.7 on 2020-03-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_auto_20191218_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsRollback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('jobname', models.CharField(max_length=64, unique=True, verbose_name='jenkins任务名称')),
                ('build_number', models.IntegerField(verbose_name='jenkins最后发布成功的buildID')),
            ],
            options={
                'verbose_name_plural': 'jenkins回滚ID表',
            },
        ),
        migrations.CreateModel(
            name='JenkinsStauts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('gid', models.CharField(max_length=64, verbose_name='工单id')),
                ('jobname', models.CharField(max_length=64, verbose_name='jenkins任务名称')),
                ('buidnumber', models.IntegerField(verbose_name='jenkins任务构建ID')),
                ('countnumber', models.IntegerField(null=True, verbose_name='工单包含的任务数')),
                ('status', models.CharField(max_length=10, null=True, verbose_name='job最终发布状态')),
            ],
            options={
                'verbose_name_plural': 'jobs发布状态表',
            },
        ),
        migrations.AlterField(
            model_name='subproject',
            name='name',
            field=models.CharField(max_length=32, verbose_name='项目名'),
        ),
    ]
