# Generated by Django 2.1.7 on 2020-03-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_auto_20200311_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='ConfigCenter',
            field=models.CharField(max_length=128, null=True, verbose_name='配置中心文件'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='PackageName',
            field=models.CharField(max_length=64, null=True, verbose_name='编译target目录'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='ProjectName',
            field=models.CharField(max_length=64, null=True, verbose_name='项目目录'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='ansible_group',
            field=models.CharField(max_length=64, null=True, verbose_name='ansible主机组名称'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='command',
            field=models.CharField(max_length=512, null=True, verbose_name='项目命令'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='env',
            field=models.CharField(max_length=32, null=True, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='git_address',
            field=models.CharField(max_length=512, null=True, verbose_name='git地址'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='interface_name',
            field=models.CharField(max_length=32, null=True, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='job_name',
            field=models.CharField(max_length=64, null=True, verbose_name='jobname'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='label',
            field=models.CharField(max_length=32, null=True, verbose_name='maven编译标签'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='webapp_dir',
            field=models.CharField(max_length=128, null=True, verbose_name='项目存放路径'),
        ),
    ]
