# Generated by Django 2.1.7 on 2020-03-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20200311_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='domain',
            field=models.CharField(max_length=64, null=True, verbose_name='项目域名'),
        ),
    ]
