# Generated by Django 2.1.7 on 2020-03-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0012_auto_20200326_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('jobs_name', models.CharField(max_length=64, unique=True, verbose_name='jenkins任务名称')),
                ('pid', models.IntegerField(null=True, verbose_name='项目ID')),
                ('describe', models.CharField(max_length=225, null=True, verbose_name='jenkins描述')),
                ('env', models.SmallIntegerField(choices=[(1, '预生产环境'), (2, '生产环境')], default=1, verbose_name='环境')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobsNameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('domain', models.CharField(max_length=64, null=True, verbose_name='项目域名')),
                ('type', models.SmallIntegerField(choices=[(1, 'static'), (2, 'tomcat'), (3, 'python'), (4, 'go')], default=2, verbose_name='项目类型')),
                ('command', models.CharField(max_length=512, null=True, verbose_name='项目命令')),
                ('git_address', models.CharField(max_length=512, null=True, verbose_name='git地址')),
                ('interface_name', models.CharField(max_length=32, null=True, verbose_name='接口名称')),
                ('jobs_name', models.CharField(max_length=64, null=True, verbose_name='jobs_name')),
                ('label', models.CharField(max_length=32, null=True, verbose_name='maven编译标签')),
                ('ConfigCenter', models.CharField(max_length=128, null=True, verbose_name='配置中心文件')),
                ('PackageName', models.CharField(max_length=64, null=True, verbose_name='编译target目录')),
                ('ProjectName', models.CharField(max_length=64, null=True, verbose_name='项目目录')),
                ('webapp_dir', models.CharField(max_length=128, null=True, verbose_name='项目存放路径')),
                ('ansible_group', models.CharField(max_length=64, null=True, verbose_name='ansible主机组名称')),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.JobsName', verbose_name='jobs名称表')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='JenkinsStauts',
            new_name='JenkinsStatus',
        ),
        migrations.RenameField(
            model_name='jenkinsrollback',
            old_name='jobname',
            new_name='jobs_name',
        ),
        migrations.RenameField(
            model_name='jenkinsstatus',
            old_name='buidnumber',
            new_name='build_number',
        ),
        migrations.RenameField(
            model_name='jenkinsstatus',
            old_name='countnumber',
            new_name='count_number',
        ),
        migrations.RenameField(
            model_name='jenkinsstatus',
            old_name='jobname',
            new_name='jobs_name',
        ),
    ]
