# Generated by Django 2.1.7 on 2020-03-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0013_auto_20200330_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsnameinfo',
            name='jid',
        ),
        migrations.DeleteModel(
            name='JobsName',
        ),
        migrations.DeleteModel(
            name='JobsNameInfo',
        ),
    ]
