# Generated by Django 2.1.7 on 2020-03-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0014_auto_20200330_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='环境')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='env',
        ),
        migrations.AddField(
            model_name='subproject',
            name='env',
            field=models.ManyToManyField(null=True, to='deploy.Env', verbose_name='环境'),
        ),
    ]
