# Generated by Django 2.1.7 on 2020-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0015_auto_20200330_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='env',
            field=models.ManyToManyField(to='deploy.Env', verbose_name='环境'),
        ),
    ]
