# Generated by Django 2.1.7 on 2020-06-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0016_auto_20200520_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shortName',
            field=models.CharField(max_length=15, null=True, verbose_name='项目简称'),
        ),
    ]
