# Generated by Django 2.1.7 on 2020-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0017_project_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shortName',
            field=models.CharField(max_length=15, unique=True, verbose_name='项目简称'),
        ),
    ]
