# Generated by Django 2.1.7 on 2020-06-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0018_auto_20200610_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='env',
        ),
        migrations.AddField(
            model_name='subproject',
            name='env',
            field=models.SmallIntegerField(choices=[(1, '预生产环境'), (2, '生产环境')], default=1, verbose_name='发布环境'),
        ),
        migrations.DeleteModel(
            name='Env',
        ),
    ]
