# Generated by Django 2.1.7 on 2020-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0019_auto_20200612_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='env',
            field=models.SmallIntegerField(choices=[(1, '预生产环境'), (2, '生产环境'), (3, '测试环境'), (4, '开发环境')], default=1, verbose_name='发布环境'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='job_name',
            field=models.CharField(max_length=64, null=True, verbose_name='jobsName'),
        ),
    ]
