# Generated by Django 2.1.7 on 2023-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0021_remove_subproject_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_load_balancing',
            field=models.BooleanField(default=False, verbose_name='是否负载均衡'),
        ),
    ]
